lookify/lookify/urls.py
from django.contrib import admin
from django.conf.urls import handler404
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView

from users.forms import LoginForm

def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

handler404 = custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('opportunity/', include('opportunity.urls')),
    path('dashboard/', include('dashboard.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('org/', include('orgs.urls')),
    path('notif/', include('notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lookify/orgs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.org_home, name="org-home")
]

lookify/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.home, name='users-home'),
    path('register/',views.RegisterView.as_view(), name='users-register'),
    path('profile/<str:username>', views.profile_view, name='profile-view'),
    path('find_users/', views.user_search, name="find-users"),
    path('ajax/school-search/', views.SchoolAjaxView.as_view(), name='school_ajax_search'),
    path("school/add",views.addSchool,name="add-school"),
    path('login/modal', views.ModalSignInView.as_view(), name="signin-modal"),
    path('update/indv', views.ProfileUpdate.as_view(), name='update_profile'),
    path('update/org', views.OrgProfileUpdate.as_view(), name='update-org-profile'),
    path('submit_message/<str:receiver>', views.submitContact, name="submit_message"),
    path("create_exp/", views.expo, name="create-exp"),
    path("create_edu/", views.edu, name="create-edu"),
    path("check_username/", views.check_username, name="check-username"),
    path("check_email/", views.check_email, name="check-email"),
    path("tutorial/", views.tutorial, name="tutorial"),
    path("sendtest", views.send_lookify_email, name="send-lookify-email"),
    path("password_reset", views.password_reset,name="password-reset" ),
    path('password_reset/done/', TemplateView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', TemplateView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lookify/opportunity/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
# Create your models here.
from taggit.managers import TaggableManager
from PIL import Image
class Opportunity(models.Model):
    CATEGORY_CHOICES = [
        ('academic_enrichment', 'Academic Enrichment'),
        ('extracurricular_activities', 'Extracurricular Activities'),
        ('stem', 'STEM'),
        ('internships_work_experience', 'Internships and Work Experience'),
        ('community_service_volunteering', 'Community Service and Volunteering'),
        ('leadership_development', 'Leadership Development'),
        ('college_career_readiness', 'College and Career Readiness'),
        ('personal_development', 'Personal Development'),
        ('cultural_global_awareness', 'Cultural and Global Awareness'),
        ('health_wellness', 'Health and Wellness'),
        ('arts_creativity', 'The Arts and Creativity'),
    ]
    LENGTH_CHOICES = [
        ('less_than_a_week', 'Less than a week'),
        ('one_week_to_four', '1-4 weeks'),
        ('one_month_to_three', '1-3 months'),
        ('three_month_to_six', '3-6 months'),
        ('six_month_plus', '6+ months'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=50, default="New York, NY")
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='academic_enrichment')
    background = models.ImageField(default='default.jpg', upload_to='background_images')
    responsibilities = models.TextField(default="Add responsibilities for this responsibility")
    application_type = models.URLField(blank=True, null=True) 
    grade = models.CharField(max_length=35, default="10th Grade")
    length = models.CharField(max_length=50, choices=LENGTH_CHOICES, default='less_than_a_week')
    pub_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    like = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, max_length=100)
    num_applications = models.IntegerField(default=0)
    tags = TaggableManager()
    visits = models.IntegerField(default = 0)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.updated_date = timezone.now()
        super().save(*args, **kwargs)


class Experience(models.Model):
    experience1 = models.CharField(max_length=50, default="mcd")
    experience2 = models.CharField(max_length=50, default="tagerty")

    def __str__(self):
        return (self.experience1 + " " + self.experience2)

class Application(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending' ),
        ('ACCEPTED', 'Accepted'),
        ('REJECTED', 'Rejected')
        ]
    opportunity = models.ForeignKey(Opportunity, on_delete=models.CASCADE)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    send_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25, choices = STATUS_CHOICES, default='PENDING')
    contact = models.TextField()

lookify/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from django.utils import timezone
from django.conf import settings
from taggit.managers import TaggableManager


class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = [
        ('individual', 'Individual'),
        ('organization', 'Organization'),
    ]
    
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, default='individual')

    def __str__(self):
        return self.username


def profile_image_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/profile_images/<filename>
    return f"profile_images/{filename}"

def background_image_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/background_images/<filename>
    return f"background_images/{filename}"
class School(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    background = models.ImageField(default="default.jpg", upload_to="profile_background")
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=75, blank=True)
    bio = models.TextField()
    grade = models.TextField(default='N/A')
    
    school = models.ForeignKey('School', null=True, blank=True, on_delete=models.SET_NULL, default=None)
    skills = TaggableManager()
    has_applied = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

class OrganizationProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    organization_name = models.CharField(max_length=50, default="N/A")
    background = models.ImageField(default="default.jpg", upload_to="profile_background")
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=75, blank=True)
    school = school = models.ForeignKey('School', null=True, blank=True, on_delete=models.SET_NULL, default=None)
    about = models.TextField()
    full_address = models.TextField(default='N/A')
    website = models.URLField(blank=True)
    domain = models.CharField(max_length=70, default="N/A")
    keywords = TaggableManager()

    def __str__(self):
        return self.organization_name

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)
class Experience(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    org = models.CharField(max_length=25)
    time_period = models.CharField(max_length=10)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.title
    
class Education(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    inst = models.CharField(max_length=25)
    time_period = models.CharField(max_length=10)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.title

class ContactRequest(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sent_contact_requests')
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='received_contact_requests')
    email = models.CharField(max_length=50)
    message = models.TextField()
    send_date =  models.DateTimeField(auto_now_add=True)

class Exp(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=50, default="New York, NY")
    length = models.CharField(max_length=50, default='less_than_a_week')
    slug = models.SlugField(unique=True, max_length=100)
    num_applications = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Edu(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=50, default="New York, NY")
    length = models.CharField(max_length=50, default='less_than_a_week')
    slug = models.SlugField(unique=True, max_length=100)
    num_applications = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

lookify/templates/users/change_password.html
{% extends "base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

lookify/templates/users/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    {% comment %} <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Thanks for your time, contact me for any comments or suggestions using my email address.
        </p>
        <br><hr><a href="{% url 'login' %}" class="btn btn-primary">Sign in again</a>
        </div>
    </div>
 {% endcomment %}

{% endblock content %}

lookify/templates/users/modal_signin.html
{% extends "base.html" %}
{% block content %}

<form class="mt-4" hx-post="{{request.path}}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
    {% csrf_token %}
    <div class="form-floating mb-3">
        {{form.username}}
        <label for="pxp-signin-email">Email address</label>
        <span class="fa fa-envelope-o"></span>
    </div>
    <div class="form-floating mb-3">
        {{form.password}}
        <label for="pxp-signin-password">Password</label>
        <span class="fa fa-lock"></span>
    </div>
    <div class="form-floating mb-3">
        {{ form.remember_me}}
        <label for="pxp-signin-page-email">Remember Me</label>
    </div>
    <a href="#" class="btn rounded-pill pxp-modal-cta">Continue</a>
    <div class="mt-4 text-center pxp-modal-small">
        <a href="#" class="pxp-modal-link">Forgot password</a>
    </div>
    <div class="mt-4 text-center pxp-modal-small">
        New to Jobster? <a role="button" class="" data-bs-target="#pxp-signup-modal" data-bs-toggle="modal" data-bs-dismiss="modal">Create an account</a>
    </div>
</form>
{% endblock%}

lookify/templates/users/org_profile_view.html
{% extends 'base.html' %}
{% block title %} Organization Profile {% endblock %}
{% block icon %}
{% if request.user.is_authenticated %}
    <a href= "{% url 'create-opp'%}" class="btn rounded-pill pxp-nav-btn">Post Look</a>
    <div class="dropdown pxp-user-nav-dropdown pxp-user-notifications">
        <a role="button" class="dropdown-toggle" data-bs-toggle="dropdown">
            <span class="fa fa-bell-o"></span>
            <div class="pxp-user-notifications-counter">{{notifs_count}}</div>
        </a>
        <ul class="dropdown-menu dropdown-menu-end pxp-user-notifications">
            {% for notif in notifs %}
            <li class="notification {% if not notif.is_read %} unread{% endif %}" data-id="{{ notif.id }}">
                {% if notif.type_of_notification == 'dm' %}
                    <a class="dropdown-item" href="{% url 'inbox' %}">
                        <strong>{{ notif.user_sender }}</strong> 
                            wants to get in touch with you
                        <span class="pxp-is-time">{{ notif.created_at|timesince }} ago</span>
                    </a>
                {% elif notif.type_of_notification == "application" %}
                    <a class="dropdown-item" href="{% url 'opportunity-manager' %}">
                        <strong>{{ notif.user_sender }}</strong> 
                            applied to one of your looks
                        <span class="pxp-is-time">{{ notif.created_at|timesince }} ago</span>
                    </a>
                {% elif notif.type_of_notification == "result" %}
                    <a class="dropdown-item" href="{% url 'application-manager' %}">
                        <strong>{{ notif.user_sender }}</strong> 
                            gave you a response to your application
                        <span class="pxp-is-time">{{ notif.created_at|timesince }} ago</span>
                    </a>
                {% endif %}
                
            </li>
            {% endfor %}
            
        </ul>
        
    </div>
    <div class="dropdown pxp-user-nav-dropdown">
        <a href="index.html" class="dropdown-toggle" data-bs-toggle="dropdown">
            {% if request.user.user_type == 'individual' %}
            <div class="pxp-user-nav-avatar pxp-cover" style="background-image: url({{ request.user.profile.avatar.url }})"></div>
            {% else %}
            <div class="pxp-user-nav-avatar pxp-cover" style="background-image: url({{ request.user.organizationprofile.avatar.url }})"></div>
            {% endif %}
            <div class="pxp-user-nav-name d-none d-md-block">
                {{ request.user.username }}
            </div>
        </a>
        
        <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{% url 'profile-view' request.user.username %}">See Profile</a></li>
            <li><a role = "button" class = "nav-link" href="{% url 'user-dash'%}" >Dashboard</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
    {% else %}
    <a href= "{% url 'users-register'%}" class="btn rounded-pill pxp-nav-btn">Register</a>
    <a class="btn rounded-pill pxp-user-nav-trigger"  href="{% url 'login' %}">Sign in</a>
    {% endif %}
{% endblock icon %}
{% block content %}
        <section>
            <div class="pxp-container">
                <div class="pxp-single-company-container pxp-has-columns">
                    <div class="row">
                        <div class="col-lg-7 col-xl-8 col-xxl-9">
                            <div class="pxp-single-company-hero pxp-cover pxp-boxed" style="background-image: url({{ org.background.url }});">
                                <div class="pxp-hero-opacity"></div>
                                <div class="pxp-single-company-hero-caption">
                                    <div class="pxp-container">
                                        <div class="pxp-single-company-hero-content">
                                            <div class="pxp-single-company-hero-logo" style="background-image: url({{ org.avatar.url}});"></div>
                                            <div class="pxp-single-company-hero-title">
                                                <h1>{{org.organization_name}}</h1>
                                                <div class="pxp-single-company-hero-location"><span class="fa fa-globe"></span>{{org.full_address}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <section class="mt-4 mt-lg-5">
                                <div class="pxp-single-company-content">
                                    <h2>About {{org.organization_name}}</h2>
                                    <p>{{org.about}}</p>

                                </div>
                            </section>
                        </div>
                        <div class="col-lg-5 col-xl-4 col-xxl-3">
                            <div class="pxp-single-company-side-panel mt-5 mt-lg-0">
                                <div class="mt-4">
                                    <div class="pxp-single-company-side-info-label pxp-text-light">Focus</div>
                                    <div class="pxp-single-company-side-info-data">{{org.domain}}</div>
                                </div>
                                <div class="mt-4">
                                    <div class="pxp-single-company-side-info-label pxp-text-light">Phone</div>
                                    <div class="pxp-single-company-side-info-data">{{org.phone}}</div>
                                </div>
                                <div class="mt-4">
                                    <div class="pxp-single-company-side-info-label pxp-text-light">Email</div>
                                    <div class="pxp-single-company-side-info-data">{{org.email}}</div>
                                </div>
                                {% if org.school != None %}
                                    <div class="mt-4">
                                        <div class="pxp-single-company-side-info-label pxp-text-light">School</div>
                                        <div class="pxp-single-company-side-info-data">{{org.school}}</div>
                                    </div>
                                {% endif %}
                                <div class="mt-4">
                                    <div class="pxp-single-company-side-info-label pxp-text-light">Location</div>
                                    <div class="pxp-single-company-side-info-data">{{org.full_address}}</div>
                                </div>
                                <div class="mt-4">
                                    <div class="pxp-single-company-side-info-label pxp-text-light">Website</div>
                                    <div class="pxp-single-company-side-info-data"><a href="{{org.website}}" target="_blank">{{org.website}}</a></div>
                                </div>
                                <!--<div class="mt-4">-->
                                <!--    <div class="pxp-single-company-side-info-data">-->
                                <!--        <ul class="list-unstyled pxp-single-company-side-info-social">-->
                                <!--            <li><a href="#"><span class="fa fa-facebook"></span></a></li>-->
                                <!--            <li><a href="#"><span class="fa fa-twitter"></span></a></li>-->
                                <!--            <li><a href="#"><span class="fa fa-instagram"></span></a></li>-->
                                <!--            <li><a href="#"><span class="fa fa-linkedin"></span></a></li>-->
                                <!--        </ul>-->
                                <!--    </div>-->
                                <!--</div>-->
                            </div>
                            <p> </p>
                            {% if org.user != request.user%}
                            <div class="pxp-single-company-side-panel mt-4 mt-lg-5">
                                <h3>Contact {{org.user.organizationprofile.organization_name}}</h3>
                                <form class="mt-4" method="POST" action="{% url "submit_message" receiver=user %}">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="contact-candidate-email" class="form-label" >Email</label>
                                        <input type="text" class="form-control" id="contact-candidate-email" name="email" placeholder="Enter your email address">
                                    </div>
                                    <div class="mb-3">
                                        <label for="contact-candidate-message" class="form-label">Message</label>
                                        <textarea class="form-control" id="contact-candidate-message" name="message" placeholder="Type your message here..."></textarea>
                                    </div>
                                    <button type="submit" class="btn rounded-pill pxp-section-cta d-block">Send Message</button>
                                </form>
                            </div>
                            {% else %}
                            <div class="pxp-single-company-side-panel mt-4 mt-lg-5">
                                <h3>Check your <a href="{% url 'inbox' %}">inbox</a> for messages</h3>

                            </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="mt-100">
            <div class="pxp-container">
                <h2 class="pxp-subsection-h2">Available Opportunities</h2>
                <p class="pxp-text-light">Opportunities list posted by {{org.organization_name}}</p>

                <div class="row mt-3 mt-md-4 pxp-animate-in pxp-animate-in-top pxp-in">
                    {% for post in posts %}
                    <div class="col-xl-6 pxp-jobs-card-2-container">
                        <div class="pxp-jobs-card-2 pxp-has-border">
                            <div class="pxp-jobs-card-2-top">
                                <a href="{% url 'post-detail' pk=post.pk %}" class="pxp-jobs-card-2-company-logo" style="background-image: url({{post.background.url}});"></a>
                                <div class="pxp-jobs-card-2-info">
                                    <a href="{% url 'post-detail' pk=post.pk %}" class="pxp-jobs-card-2-title">{{post.title}}</a>
                                    <div class="pxp-jobs-card-2-details">
                                        <a href="{% url 'post-detail' pk=post.pk %}" class="pxp-jobs-card-2-location">
                                            <span class="fa fa-globe"></span>{{post.location}}
                                        </a>
                                        <div class="pxp-jobs-card-2-type">{{post.get_length_display}}</div>
                                    </div>
                                </div>
                            </div>
                            <div class="pxp-jobs-card-2-bottom">

                                    <div class="pxp-jobs-card-2-category-label">{{post.get_category_display}}</div>

                                <div class="pxp-jobs-card-2-bottom-right">
                                    <span class="pxp-jobs-card-2-date pxp-text-light">{{post.pub_date|timesince}} ago by</span> <a href="{% url 'profile-view' username=post.user.username %}" class="pxp-jobs-card-2-company">{{org.organization_name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </section>

{% endblock %}

lookify/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %} Password Reset Done {% endblock title %}

{% block content %}
<section class="mt-100">
    <div class=" pxp-column pxp-is-light">
    <div class="pxp-container">
        <h2 class="pxp-section-h2">Password reset complete</h2>
        <p class="pxp-text-light">
           Your password has been reset, please return home and log in again
        </p>
        <a href='{% url 'login' %}'><button name="return-home" id="return-home" class="btn rounded-pill pxp-sign-hero-form-cta">Login</button></a>
    </div>
</div>
</section>

{% endblock %}