lookify/lookify/urls.py
from django.contrib import admin
from django.conf.urls import handler404
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView

from users.forms import LoginForm

def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

handler404 = custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('opportunity/', include('opportunity.urls')),
    path('dashboard/', include('dashboard.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('org/', include('orgs.urls')),
    path('notif/', include('notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lookify/orgs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.org_home, name="org-home")
]

lookify/orgs/models.py
from django.db import models

# Create your models here.

lookify/orgs/forms.py
from django import forms
from django_select2 import forms as s2forms
from users.models import School

class SchoolWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
        "zip_code__icontains",
    ]
   
    def get_url(self):
        return '/ajax/school-search/'
class OrgSearchForm(forms.Form):
    search = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Organization Name or Keyword',
        'class': 'form-control'
    }))
    school = forms.ModelChoiceField(
        queryset=School.objects.all(),
        widget=SchoolWidget,
        label="Search School by Name or Zip Code"
    )

lookify/orgs/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.contrib.auth.decorators import login_required
from .forms import OrgSearchForm
from users.models import OrganizationProfile

User = get_user_model()

@login_required
def org_home(request):
    form = OrgSearchForm(request.GET or None)
    search = request.GET.get('search', '')
    school = request.GET.get('school', '')

    orgs = User.objects.filter(
        Q(user_type='organization') &
        (Q(organizationprofile__domain__icontains=search) |
         Q(organizationprofile__about__icontains=search))
    )

    if school:
        orgs = orgs.filter(organizationprofile__school_id=school)

    orgs = orgs.annotate(
        opportunity_count=Count('opportunity')  # Use the related_name if specified in the ForeignKey
    ).order_by('-opportunity_count')




    page = Paginator(orgs, 9)
    page_number = request.GET.get('page', 1)

    page_obj = page.get_page(page_number)

    context = {
        'form':form,
        'orgs': orgs,
        'page_number': page_obj,
    }
    return render(request, 'orgs/orgs-home.html', context)

lookify/templates/orgs/orgs-home.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block stylesheet %} <link rel="stylesheet" href="/static/css/customsearch.css"> {% endblock %}
{% block title %} Search Organizations {% endblock title %}
{% block content %}
<section class="pxp-page-header-simple" style="background-color: var(--pxpSecondaryColor);">
    <div class="pxp-container">
        <h1>Search Organizations</h1>
        <div class="pxp-hero-subtitle pxp-text-light">Find opportunities with your favorite organizations</div>
        <div class="pxp-hero-form pxp-hero-form-round pxp-large mt-3 mt-lg-4">
            <form id="general" method="GET" class="row gx-3 align-items-center" style="display: show;">
                <div class="col-12 col-lg">
                    <div class="input-group mb-3 mb-lg-0">
                        <span class="input-group-text"><span class="fa fa-search"></span></span>
                        {{ form.search }}
                    </div>
                </div>
                <div class="col-12 col-lg-auto">
                    <button type="submit">Find Organizations</button>
                </div>

                <!-- School Filter Switch -->
                <div class="col-12 col-lg mt-3 mt-lg-4">
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="associateSchoolSwitch" {% if form.school.value %}checked{% endif %}>
                        <label class="custom-control-label" for="associateSchoolSwitch">I want to filter for my school</label>
                    </div>
                </div>

                <!-- School Select Dropdown (hidden/shown based on the switch) -->
                <div class="col-12 col-lg mt-3 mt-lg-4" id="school-filter" style="{% if form.school.value %}display: block;{% else %}display: none;{% endif %}">
                    <div class="input-group mb-3 mb-lg-0">
                        <span class="input-group-text"><span class="fa fa-search"></span></span>
                        {{ form.school }}
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="mt-100">
    <div class="pxp-container">
        <div class="pxp-companies-list-top">
            <div class="row justify-content-between align-items-center">
                <div class="col-auto">
                    <h2><span class="pxp-text-light">Showing</span> {{orgs.count}} <span class="pxp-text-light">organizations</span></h2>
                </div>

            </div>
        </div>

        <div class="row">
            {% for org in page_number %}
            <div class="col-md-6 col-xl-4 col-xxl-3 pxp-companies-card-1-container">
                <div class="pxp-companies-card-1 pxp-has-border">
                    <div class="pxp-companies-card-1-top">
                        <a href="{% url 'profile-view' username=org.username %}" class="pxp-companies-card-1-company-logo" style="background-image: url({{org.organizationprofile.avatar.url}});"></a>
                        <a href="{% url 'profile-view' username=org.username %}" class="pxp-companies-card-1-company-name">{{org.organizationprofile.organization_name}}</a>
                        <div class="pxp-companies-card-1-company-description pxp-text-light">{{org.organizationprofile.about|truncate_words:50 }}</div>
                    </div>
                    <div class="pxp-companies-card-1-bottom">
                        <a href="{% url 'profile-view' username=org.username %}" class="pxp-companies-card-1-company-jobs">{{ org.opportunity_count }} opportunities</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="row mt-4 mt-lg-5 justify-content-between align-items-center">
            <div class="col-auto">
                <nav class="mt-3 mt-sm-0" aria-label="Companies pagination">
                    <ul class="pagination pxp-pagination">
                        {% if page_number.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_number.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                            <li class="page-item active"><a class="page-link" >{{ page_number.number }}</a></li>
                        {% if page_number.has_next %}
                            <li class="page-item">
                            <a class="page-link" href="?page={{ page_number.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="col-auto">
                <a href="#" class="btn rounded-pill pxp-section-cta mt-3 mt-sm-0">Show me more<span class="fa fa-angle-right"></span></a>
            </div>
        </div>
    </div>
</section>


 {% endblock content %}
 {% block js%}
 <script>
    $(document).ready(function() {
        // Initial setup: Show or hide the school filter based on the switch state
        toggleSchoolFilter();
    
        $('#associateSchoolSwitch').change(function() {
            toggleSchoolFilter();
        });
    
        $('#general').submit(function() {
            // If the switch is unchecked, disable the school field
            if (!$('#associateSchoolSwitch').is(':checked')) {
                $('#id_school').prop('disabled', true);
            }
        });
    
        function toggleSchoolFilter() {
            if ($('#associateSchoolSwitch').is(':checked')) {
                $('#school-filter').show();
                $('#id_school').prop('disabled', false); // Enable the school field if the switch is checked
            } else {
                $('#school-filter').hide();
                $('#id_school').val(null).trigger('change');  // Clear the school selection
                $('#id_school').prop('disabled', true); // Disable the school field to prevent submission
            }
        }
    
        $('#id_school').select2({
            ajax: {
                url: '{% url "school_ajax_search" %}',
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        q: params.term, // search term
                    };
                },
                processResults: function(data) {
                    if (data.results.length === 0) {
                        $('#add-school-btn').show();
                    } else {
                        $('#add-school-btn').hide();
                    }
                    return {
                        results: data.results,
                    };
                },
                cache: true
            },
            minimumInputLength: 1,
            width: '100%'  // Make the widget take the full width of the container
        });
    });
    
    
</script>
 {% endblock %}